<?php

use Illuminate\Database\Seeder;

class CommissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('commissions')->delete();
        
        \DB::table('commissions')->insert(array (
            0 => 
            array (
                'id' => 44,
                'user_id' => 35,
                'type_service' => 4,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 2,
                'type_payment' => 2,
                'date' => '19/02/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-18 04:17:02',
                'updated_at' => '2020-02-18 04:25:14',
            ),
            1 => 
            array (
                'id' => 45,
                'user_id' => 35,
                'type_service' => 4,
                'type' => 1,
                'comm' => 12.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '2020-02-01',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-18 04:22:12',
                'updated_at' => '2020-02-18 04:26:58',
            ),
            2 => 
            array (
                'id' => 46,
                'user_id' => 36,
                'type_service' => 6,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-18 07:12:23',
                'updated_at' => '2020-02-18 07:12:23',
            ),
            3 => 
            array (
                'id' => 47,
                'user_id' => 36,
                'type_service' => 5,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-18 07:12:23',
                'updated_at' => '2020-02-18 07:12:23',
            ),
            4 => 
            array (
                'id' => 48,
                'user_id' => 36,
                'type_service' => 4,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-18 07:12:23',
                'updated_at' => '2020-02-18 07:12:23',
            ),
            5 => 
            array (
                'id' => 49,
                'user_id' => 37,
                'type_service' => 6,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '15/07/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-21 16:57:00',
            ),
            6 => 
            array (
                'id' => 50,
                'user_id' => 37,
                'type_service' => 4,
                'type' => 2,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-09 19:12:24',
            ),
            7 => 
            array (
                'id' => 51,
                'user_id' => 37,
                'type_service' => 4,
                'type' => 3,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            8 => 
            array (
                'id' => 52,
                'user_id' => 37,
                'type_service' => 5,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            9 => 
            array (
                'id' => 53,
                'user_id' => 37,
                'type_service' => 6,
                'type' => 2,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            10 => 
            array (
                'id' => 54,
                'user_id' => 37,
                'type_service' => 6,
                'type' => 3,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            11 => 
            array (
                'id' => 55,
                'user_id' => 37,
                'type_service' => 8,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-09 19:15:02',
            ),
            12 => 
            array (
                'id' => 56,
                'user_id' => 37,
                'type_service' => 8,
                'type' => 2,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-09 19:14:38',
            ),
            13 => 
            array (
                'id' => 57,
                'user_id' => 37,
                'type_service' => 5,
                'type' => 2,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            14 => 
            array (
                'id' => 58,
                'user_id' => 37,
                'type_service' => 5,
                'type' => 3,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-09 19:14:21',
            ),
            15 => 
            array (
                'id' => 59,
                'user_id' => 37,
                'type_service' => 7,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-09-09 19:13:47',
            ),
            16 => 
            array (
                'id' => 60,
                'user_id' => 37,
                'type_service' => 7,
                'type' => 2,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            17 => 
            array (
                'id' => 61,
                'user_id' => 37,
                'type_service' => 7,
                'type' => 3,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-19 04:03:27',
                'updated_at' => '2020-02-19 04:03:27',
            ),
            18 => 
            array (
                'id' => 62,
                'user_id' => 38,
                'type_service' => 6,
                'type' => 1,
                'comm' => 56.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-19 15:27:44',
                'updated_at' => '2020-09-21 12:24:53',
            ),
            19 => 
            array (
                'id' => 63,
                'user_id' => 39,
                'type_service' => 4,
                'type' => 1,
                'comm' => 17.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-20 09:10:15',
                'updated_at' => '2020-09-19 13:46:09',
            ),
            20 => 
            array (
                'id' => 64,
                'user_id' => 39,
                'type_service' => 6,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-20 09:10:15',
                'updated_at' => '2020-09-19 13:45:36',
            ),
            21 => 
            array (
                'id' => 65,
                'user_id' => 39,
                'type_service' => 5,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-20 09:10:15',
                'updated_at' => '2020-09-19 13:46:31',
            ),
            22 => 
            array (
                'id' => 66,
                'user_id' => 42,
                'type_service' => 4,
                'type' => 1,
                'comm' => 17.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '21/02/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-21 06:19:42',
                'updated_at' => '2020-09-19 13:48:49',
            ),
            23 => 
            array (
                'id' => 67,
                'user_id' => 44,
                'type_service' => 4,
                'type' => 1,
                'comm' => 13.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-21 09:11:58',
                'updated_at' => '2020-02-21 09:11:58',
            ),
            24 => 
            array (
                'id' => 68,
                'user_id' => 44,
                'type_service' => 6,
                'type' => 1,
                'comm' => 13.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-21 09:11:58',
                'updated_at' => '2020-02-21 09:11:58',
            ),
            25 => 
            array (
                'id' => 69,
                'user_id' => 44,
                'type_service' => 5,
                'type' => 1,
                'comm' => 13.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-21 09:11:58',
                'updated_at' => '2020-02-21 09:11:58',
            ),
            26 => 
            array (
                'id' => 70,
                'user_id' => 46,
                'type_service' => 4,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '22/02/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-02-22 03:20:13',
                'updated_at' => '2020-02-22 03:20:13',
            ),
            27 => 
            array (
                'id' => 71,
                'user_id' => 47,
                'type_service' => 4,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '22/02/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-22 03:28:09',
                'updated_at' => '2020-02-22 03:28:09',
            ),
            28 => 
            array (
                'id' => 72,
                'user_id' => 47,
                'type_service' => 5,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '21/02/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-02-22 03:28:09',
                'updated_at' => '2020-02-22 03:28:09',
            ),
            29 => 
            array (
                'id' => 73,
                'user_id' => 48,
                'type_service' => 4,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:03:25',
                'updated_at' => '2020-09-09 19:03:25',
            ),
            30 => 
            array (
                'id' => 74,
                'user_id' => 48,
                'type_service' => 5,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:03:25',
                'updated_at' => '2020-09-09 19:13:14',
            ),
            31 => 
            array (
                'id' => 75,
                'user_id' => 48,
                'type_service' => 6,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:03:25',
                'updated_at' => '2020-09-09 19:03:25',
            ),
            32 => 
            array (
                'id' => 76,
                'user_id' => 48,
                'type_service' => 7,
                'type' => 1,
                'comm' => 12.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:03:25',
                'updated_at' => '2020-09-09 19:03:25',
            ),
            33 => 
            array (
                'id' => 77,
                'user_id' => 48,
                'type_service' => 8,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:03:25',
                'updated_at' => '2020-09-09 19:13:05',
            ),
            34 => 
            array (
                'id' => 78,
                'user_id' => 48,
                'type_service' => 6,
                'type' => 2,
                'comm' => 12.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:06:10',
                'updated_at' => '2020-09-09 19:06:10',
            ),
            35 => 
            array (
                'id' => 79,
                'user_id' => 48,
                'type_service' => 6,
                'type' => 3,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 2,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:06:57',
                'updated_at' => '2020-09-09 19:12:53',
            ),
            36 => 
            array (
                'id' => 80,
                'user_id' => 48,
                'type_service' => 4,
                'type' => 2,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:07:26',
                'updated_at' => '2020-09-09 19:07:26',
            ),
            37 => 
            array (
                'id' => 81,
                'user_id' => 48,
                'type_service' => 4,
                'type' => 3,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '09/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-09 19:08:01',
                'updated_at' => '2020-09-09 19:08:01',
            ),
            38 => 
            array (
                'id' => 82,
                'user_id' => 42,
                'type_service' => 6,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '10/09/2020',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-10 19:50:50',
                'updated_at' => '2020-09-19 13:49:02',
            ),
            39 => 
            array (
                'id' => 83,
                'user_id' => 39,
                'type_service' => 8,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/09/2019',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 13:47:03',
                'updated_at' => '2020-09-19 13:47:03',
            ),
            40 => 
            array (
                'id' => 84,
                'user_id' => 39,
                'type_service' => 7,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/09/2019',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 13:47:37',
                'updated_at' => '2020-09-19 13:47:37',
            ),
            41 => 
            array (
                'id' => 85,
                'user_id' => 42,
                'type_service' => 5,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/09/2019',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 13:50:17',
                'updated_at' => '2020-09-19 13:50:17',
            ),
            42 => 
            array (
                'id' => 86,
                'user_id' => 49,
                'type_service' => 4,
                'type' => 1,
                'comm' => 17.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:42:04',
                'updated_at' => '2020-09-19 17:42:04',
            ),
            43 => 
            array (
                'id' => 87,
                'user_id' => 49,
                'type_service' => 6,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:42:04',
                'updated_at' => '2020-09-19 17:42:04',
            ),
            44 => 
            array (
                'id' => 88,
                'user_id' => 49,
                'type_service' => 5,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:42:04',
                'updated_at' => '2020-09-19 17:42:04',
            ),
            45 => 
            array (
                'id' => 89,
                'user_id' => 49,
                'type_service' => 7,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:42:04',
                'updated_at' => '2020-09-19 17:42:04',
            ),
            46 => 
            array (
                'id' => 90,
                'user_id' => 50,
                'type_service' => 4,
                'type' => 1,
                'comm' => 17.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:55:49',
                'updated_at' => '2020-09-19 17:55:49',
            ),
            47 => 
            array (
                'id' => 91,
                'user_id' => 50,
                'type_service' => 5,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:55:49',
                'updated_at' => '2020-09-19 17:55:49',
            ),
            48 => 
            array (
                'id' => 92,
                'user_id' => 50,
                'type_service' => 6,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:55:49',
                'updated_at' => '2020-09-19 17:55:49',
            ),
            49 => 
            array (
                'id' => 93,
                'user_id' => 50,
                'type_service' => 7,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:55:49',
                'updated_at' => '2020-09-19 17:55:49',
            ),
            50 => 
            array (
                'id' => 94,
                'user_id' => 50,
                'type_service' => 8,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-19 17:55:49',
                'updated_at' => '2020-09-19 17:55:49',
            ),
            51 => 
            array (
                'id' => 95,
                'user_id' => 38,
                'type_service' => 4,
                'type' => 1,
                'comm' => 5.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '24/09/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-20 19:40:57',
                'updated_at' => '2020-09-20 19:40:57',
            ),
            52 => 
            array (
                'id' => 96,
                'user_id' => 38,
                'type_service' => 4,
                'type' => 2,
                'comm' => 123.0,
                'unit' => NULL,
                'donvi' => 2,
                'type_payment' => 1,
                'date' => '22/09/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-21 12:24:37',
                'updated_at' => '2020-09-21 12:24:37',
            ),
            53 => 
            array (
                'id' => 97,
                'user_id' => 37,
                'type_service' => 4,
                'type' => 1,
                'comm' => 16.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/09/2021',
                'gst' => 1,
                'status' => 1,
                'created_at' => '2020-09-21 15:03:41',
                'updated_at' => '2020-09-21 15:11:03',
            ),
            54 => 
            array (
                'id' => 98,
                'user_id' => 51,
                'type_service' => 6,
                'type' => 1,
                'comm' => 15.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/09/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-22 17:04:38',
                'updated_at' => '2020-09-22 17:04:38',
            ),
            55 => 
            array (
                'id' => 99,
                'user_id' => 51,
                'type_service' => 9,
                'type' => 1,
                'comm' => 10.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '22/09/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-09-22 17:05:12',
                'updated_at' => '2020-09-22 17:05:12',
            ),
            56 => 
            array (
                'id' => 100,
                'user_id' => 38,
                'type_service' => 10,
                'type' => 1,
                'comm' => 2.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '01/01/2020',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-10-12 15:12:14',
                'updated_at' => '2020-10-12 15:12:14',
            ),
            57 => 
            array (
                'id' => 101,
                'user_id' => 37,
                'type_service' => 10,
                'type' => 1,
                'comm' => 2.0,
                'unit' => NULL,
                'donvi' => 1,
                'type_payment' => 1,
                'date' => '2020-10-13',
                'gst' => 0,
                'status' => 1,
                'created_at' => '2020-10-13 16:11:46',
                'updated_at' => '2020-10-14 21:37:32',
            ),
        ));
        
        
    }
}