<?php

use Illuminate\Database\Seeder;

class ConfsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('confs')->delete();
        
        \DB::table('confs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'service_id' => 4,
                'benefit_id' => 1,
                'note' => '100% of the MBS fee',
                'note_cn' => '100％的MBS费用',
                'note_vi' => '100% phí MBS',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-07-31 03:57:29',
                'updated_at' => '2019-08-19 08:19:26',
            ),
            1 => 
            array (
                'id' => 2,
                'service_id' => 4,
                'benefit_id' => 2,
                'note' => '85% of the MBS fee',
                'note_cn' => '85％的MBS费用',
                'note_vi' => '85% phí MBS',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:15:36',
                'updated_at' => '2019-08-19 08:19:48',
            ),
            2 => 
            array (
                'id' => 3,
                'service_id' => 4,
                'benefit_id' => 3,
                'note' => '85% of the MBS fee',
                'note_cn' => '85％的MBS费用',
                'note_vi' => '85% phí MBS',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:15:50',
                'updated_at' => '2019-08-19 08:20:07',
            ),
            3 => 
            array (
                'id' => 4,
                'service_id' => 4,
                'benefit_id' => 4,
                'note' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_cn' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_vi' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:16:01',
                'updated_at' => '2020-09-25 17:58:45',
            ),
            4 => 
            array (
                'id' => 5,
                'service_id' => 4,
                'benefit_id' => 5,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:16:06',
                'updated_at' => '2019-08-19 08:16:06',
            ),
            5 => 
            array (
                'id' => 6,
                'service_id' => 4,
                'benefit_id' => 6,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:16:13',
                'updated_at' => '2019-08-19 08:16:13',
            ),
            6 => 
            array (
                'id' => 7,
                'service_id' => 5,
                'benefit_id' => 1,
                'note' => '100% of the MBS fee',
                'note_cn' => '100% of the MBS fee',
                'note_vi' => '100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:16:27',
                'updated_at' => '2019-10-07 04:01:49',
            ),
            7 => 
            array (
                'id' => 8,
                'service_id' => 6,
                'benefit_id' => 1,
                'note' => '100% of the MBS fee',
                'note_cn' => '100% of the MBS fee',
                'note_vi' => '100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-08-19 08:16:41',
                'updated_at' => '2019-10-07 04:02:11',
            ),
            8 => 
            array (
                'id' => 9,
                'service_id' => 8,
                'benefit_id' => 8,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:48:56',
                'updated_at' => '2019-10-07 03:50:47',
            ),
            9 => 
            array (
                'id' => 10,
                'service_id' => 4,
                'benefit_id' => 8,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:51:19',
                'updated_at' => '2019-10-07 03:51:19',
            ),
            10 => 
            array (
                'id' => 11,
                'service_id' => 5,
                'benefit_id' => 8,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:51:40',
                'updated_at' => '2019-10-07 03:51:40',
            ),
            11 => 
            array (
                'id' => 12,
                'service_id' => 6,
                'benefit_id' => 8,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:51:57',
                'updated_at' => '2019-10-07 03:51:57',
            ),
            12 => 
            array (
                'id' => 13,
                'service_id' => 7,
                'benefit_id' => 8,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:52:07',
                'updated_at' => '2019-10-07 03:52:07',
            ),
            13 => 
            array (
                'id' => 14,
                'service_id' => 4,
                'benefit_id' => 9,
                'note' => '100% of the rate determined by State and Territory',
                'note_cn' => '100% of the rate determined by State and Territory',
                'note_vi' => '100% of the rate determined by State and Territory',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:52:52',
                'updated_at' => '2019-10-07 03:52:52',
            ),
            14 => 
            array (
                'id' => 15,
                'service_id' => 5,
                'benefit_id' => 9,
                'note' => '100% of the rate determined by State and Territory',
                'note_cn' => '100% of the rate determined by State and Territory',
                'note_vi' => '100% of the rate determined by State and Territory',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:53:12',
                'updated_at' => '2019-10-07 03:53:12',
            ),
            15 => 
            array (
                'id' => 16,
                'service_id' => 6,
                'benefit_id' => 9,
                'note' => '100% of the rate determined by State and Territory',
                'note_cn' => '100% of the rate determined by State and Territory',
                'note_vi' => '100% of the rate determined by State and Territory',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:53:34',
                'updated_at' => '2019-10-07 03:53:34',
            ),
            16 => 
            array (
                'id' => 17,
                'service_id' => 7,
                'benefit_id' => 9,
                'note' => '100% of the rate determined by State and Territory',
                'note_cn' => '100% of the rate determined by State and Territory',
                'note_vi' => '100% of the rate determined by State and Territory',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:54:58',
                'updated_at' => '2019-10-07 03:54:58',
            ),
            17 => 
            array (
                'id' => 18,
                'service_id' => 8,
                'benefit_id' => 9,
                'note' => '100% of the rate determined by State and Territory',
                'note_cn' => '100% of the rate determined by State and Territory',
                'note_vi' => '100% of the rate determined by State and Territory',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:55:10',
                'updated_at' => '2019-10-07 03:55:10',
            ),
            18 => 
            array (
                'id' => 19,
                'service_id' => 4,
                'benefit_id' => 10,
                'note' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_cn' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_vi' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:56:51',
                'updated_at' => '2020-09-25 17:49:27',
            ),
            19 => 
            array (
                'id' => 20,
                'service_id' => 5,
                'benefit_id' => 10,
                'note' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_cn' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_vi' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:56:59',
                'updated_at' => '2020-09-25 17:50:01',
            ),
            20 => 
            array (
                'id' => 21,
                'service_id' => 6,
                'benefit_id' => 10,
                'note' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_cn' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_vi' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:57:08',
                'updated_at' => '2020-09-25 17:50:19',
            ),
            21 => 
            array (
                'id' => 22,
                'service_id' => 7,
                'benefit_id' => 10,
                'note' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_cn' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_vi' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:57:17',
                'updated_at' => '2020-09-25 17:50:38',
            ),
            22 => 
            array (
                'id' => 23,
                'service_id' => 8,
                'benefit_id' => 10,
                'note' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_cn' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'note_vi' => '100% of the charges raised by contracted private hospital. Scheduled appoitment',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:57:29',
                'updated_at' => '2020-09-25 17:50:55',
            ),
            23 => 
            array (
                'id' => 24,
                'service_id' => 4,
                'benefit_id' => 11,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:58:19',
                'updated_at' => '2020-09-25 17:51:54',
            ),
            24 => 
            array (
                'id' => 25,
                'service_id' => 5,
                'benefit_id' => 11,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:58:32',
                'updated_at' => '2020-09-25 17:52:28',
            ),
            25 => 
            array (
                'id' => 26,
                'service_id' => 6,
                'benefit_id' => 11,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:59:10',
                'updated_at' => '2020-09-25 17:52:45',
            ),
            26 => 
            array (
                'id' => 27,
                'service_id' => 7,
                'benefit_id' => 11,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:59:20',
                'updated_at' => '2020-09-25 17:53:01',
            ),
            27 => 
            array (
                'id' => 28,
                'service_id' => 8,
                'benefit_id' => 11,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 03:59:31',
                'updated_at' => '2020-09-25 17:53:16',
            ),
            28 => 
            array (
                'id' => 29,
                'service_id' => 7,
                'benefit_id' => 1,
                'note' => '100% of the MBS fee',
                'note_cn' => '100% of the MBS fee',
                'note_vi' => '100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:03:12',
                'updated_at' => '2019-10-07 04:03:12',
            ),
            29 => 
            array (
                'id' => 30,
                'service_id' => 8,
                'benefit_id' => 1,
                'note' => '100% of the MBS fee',
                'note_cn' => '100% of the MBS fee',
                'note_vi' => '100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:04:13',
                'updated_at' => '2019-10-07 04:04:13',
            ),
            30 => 
            array (
                'id' => 31,
                'service_id' => 5,
                'benefit_id' => 2,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:05:13',
                'updated_at' => '2019-10-07 04:05:13',
            ),
            31 => 
            array (
                'id' => 32,
                'service_id' => 6,
                'benefit_id' => 2,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:05:25',
                'updated_at' => '2019-10-07 04:05:25',
            ),
            32 => 
            array (
                'id' => 33,
                'service_id' => 7,
                'benefit_id' => 2,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:05:42',
                'updated_at' => '2019-10-07 04:05:42',
            ),
            33 => 
            array (
                'id' => 34,
                'service_id' => 8,
                'benefit_id' => 2,
                'note' => 'Up to 100% of the MBS fee',
                'note_cn' => 'Up to 100% of the MBS fee',
                'note_vi' => 'Up to 100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:06:29',
                'updated_at' => '2019-10-07 04:06:29',
            ),
            34 => 
            array (
                'id' => 35,
                'service_id' => 5,
                'benefit_id' => 3,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:07:18',
                'updated_at' => '2019-10-07 04:07:18',
            ),
            35 => 
            array (
                'id' => 36,
                'service_id' => 6,
                'benefit_id' => 3,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:07:32',
                'updated_at' => '2019-10-07 04:07:32',
            ),
            36 => 
            array (
                'id' => 37,
                'service_id' => 7,
                'benefit_id' => 3,
                'note' => '85% of the MBS fee',
                'note_cn' => '85% of the MBS fee',
                'note_vi' => '85% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:08:05',
                'updated_at' => '2019-10-07 04:08:05',
            ),
            37 => 
            array (
                'id' => 38,
                'service_id' => 5,
                'benefit_id' => 4,
                'note' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_cn' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_vi' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:09:27',
                'updated_at' => '2020-09-25 17:59:23',
            ),
            38 => 
            array (
                'id' => 39,
                'service_id' => 6,
                'benefit_id' => 4,
                'note' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_cn' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_vi' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 04:12:20',
                'updated_at' => '2020-09-25 17:59:38',
            ),
            39 => 
            array (
                'id' => 40,
                'service_id' => 5,
                'benefit_id' => 5,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:00',
                'updated_at' => '2019-10-07 06:27:00',
            ),
            40 => 
            array (
                'id' => 41,
                'service_id' => 6,
                'benefit_id' => 5,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:11',
                'updated_at' => '2019-10-07 06:27:11',
            ),
            41 => 
            array (
                'id' => 42,
                'service_id' => 7,
                'benefit_id' => 5,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:22',
                'updated_at' => '2019-10-07 06:27:22',
            ),
            42 => 
            array (
                'id' => 43,
                'service_id' => 8,
                'benefit_id' => 5,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:30',
                'updated_at' => '2019-10-07 06:27:30',
            ),
            43 => 
            array (
                'id' => 44,
                'service_id' => 5,
                'benefit_id' => 6,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:48',
                'updated_at' => '2019-10-07 06:27:48',
            ),
            44 => 
            array (
                'id' => 45,
                'service_id' => 6,
                'benefit_id' => 6,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:27:55',
                'updated_at' => '2019-10-07 06:27:55',
            ),
            45 => 
            array (
                'id' => 46,
                'service_id' => 7,
                'benefit_id' => 6,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:28:02',
                'updated_at' => '2019-10-07 06:28:02',
            ),
            46 => 
            array (
                'id' => 47,
                'service_id' => 8,
                'benefit_id' => 6,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:28:08',
                'updated_at' => '2019-10-07 06:28:08',
            ),
            47 => 
            array (
                'id' => 48,
                'service_id' => 8,
                'benefit_id' => 3,
                'note' => 'Up to 100% of the MBS fee',
                'note_cn' => 'Up to 100% of the MBS fee',
                'note_vi' => 'Up to 100% of the MBS fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:28:32',
                'updated_at' => '2019-10-07 06:28:32',
            ),
            48 => 
            array (
                'id' => 49,
                'service_id' => 7,
                'benefit_id' => 4,
                'note' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_cn' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_vi' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:29:08',
                'updated_at' => '2020-09-25 18:00:08',
            ),
            49 => 
            array (
                'id' => 50,
                'service_id' => 8,
                'benefit_id' => 4,
                'note' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_cn' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'note_vi' => '$50 item limit. Co-payment $40.3/each item.$300 person limit pa. $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:29:23',
                'updated_at' => '2020-09-25 18:00:29',
            ),
            50 => 
            array (
                'id' => 51,
                'service_id' => 4,
                'benefit_id' => 7,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:30:49',
                'updated_at' => '2019-10-07 06:30:49',
            ),
            51 => 
            array (
                'id' => 52,
                'service_id' => 5,
                'benefit_id' => 7,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:30:56',
                'updated_at' => '2019-10-07 06:30:56',
            ),
            52 => 
            array (
                'id' => 53,
                'service_id' => 6,
                'benefit_id' => 7,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:31:03',
                'updated_at' => '2019-10-07 06:31:03',
            ),
            53 => 
            array (
                'id' => 54,
                'service_id' => 7,
                'benefit_id' => 7,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:31:10',
                'updated_at' => '2019-10-07 06:31:10',
            ),
            54 => 
            array (
                'id' => 55,
                'service_id' => 8,
                'benefit_id' => 7,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:31:17',
                'updated_at' => '2019-10-07 06:31:17',
            ),
            55 => 
            array (
                'id' => 56,
                'service_id' => 4,
                'benefit_id' => 12,
                'note' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_cn' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_vi' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:32:14',
                'updated_at' => '2019-10-07 07:26:10',
            ),
            56 => 
            array (
                'id' => 57,
                'service_id' => 6,
                'benefit_id' => 12,
                'note' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_cn' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_vi' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:32:53',
                'updated_at' => '2019-10-07 07:33:57',
            ),
            57 => 
            array (
                'id' => 58,
                'service_id' => 8,
                'benefit_id' => 12,
                'note' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_cn' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_vi' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:33:08',
                'updated_at' => '2019-10-07 07:30:35',
            ),
            58 => 
            array (
                'id' => 59,
                'service_id' => 7,
                'benefit_id' => 12,
                'note' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_cn' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'note_vi' => '$50 item limit </br> $300 person limit pa </br> $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:33:17',
                'updated_at' => '2019-10-07 07:33:01',
            ),
            59 => 
            array (
                'id' => 60,
                'service_id' => 5,
                'benefit_id' => 12,
                'note' => '$70 item limit  </br> $300 person limit pa </br> $600 family limit pa',
                'note_cn' => '$70 item limit  </br> $300 person limit pa </br> $600 family limit pa',
                'note_vi' => '$70 item limit  </br> $300 person limit pa </br> $600 family limit pa',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:33:36',
                'updated_at' => '2019-10-07 07:35:39',
            ),
            60 => 
            array (
                'id' => 61,
                'service_id' => 4,
                'benefit_id' => 13,
                'note' => '$40.30',
                'note_cn' => '$40.30',
                'note_vi' => '$40.30',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:34:09',
                'updated_at' => '2019-10-07 06:34:09',
            ),
            61 => 
            array (
                'id' => 62,
                'service_id' => 6,
                'benefit_id' => 13,
                'note' => '$40.30',
                'note_cn' => '$40.30',
                'note_vi' => '$40.30',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:34:19',
                'updated_at' => '2019-10-07 06:34:19',
            ),
            62 => 
            array (
                'id' => 63,
                'service_id' => 7,
                'benefit_id' => 13,
                'note' => '$40.30',
                'note_cn' => '$40.30',
                'note_vi' => '$40.30',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:34:31',
                'updated_at' => '2019-10-07 06:34:31',
            ),
            63 => 
            array (
                'id' => 64,
                'service_id' => 5,
                'benefit_id' => 13,
                'note' => '$30',
                'note_cn' => '$30',
                'note_vi' => '$30',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:35:08',
                'updated_at' => '2019-10-07 06:35:08',
            ),
            64 => 
            array (
                'id' => 65,
                'service_id' => 4,
                'benefit_id' => 14,
                'note' => '2 months',
                'note_cn' => '2 months',
                'note_vi' => '2 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:35:36',
                'updated_at' => '2019-10-07 06:35:36',
            ),
            65 => 
            array (
                'id' => 66,
                'service_id' => 6,
                'benefit_id' => 14,
                'note' => '2 months',
                'note_cn' => '2 months',
                'note_vi' => '2 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:36:07',
                'updated_at' => '2019-10-07 06:36:07',
            ),
            66 => 
            array (
                'id' => 67,
                'service_id' => 7,
                'benefit_id' => 14,
                'note' => '2 months',
                'note_cn' => '2 months',
                'note_vi' => '2 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:36:25',
                'updated_at' => '2019-10-07 06:36:25',
            ),
            67 => 
            array (
                'id' => 68,
                'service_id' => 8,
                'benefit_id' => 14,
                'note' => '2 months',
                'note_cn' => '2 months',
                'note_vi' => '2 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:36:35',
                'updated_at' => '2019-10-07 06:36:35',
            ),
            68 => 
            array (
                'id' => 69,
                'service_id' => 5,
                'benefit_id' => 14,
                'note' => 'No  waiting period',
                'note_cn' => 'No  waiting period',
                'note_vi' => 'No  waiting period',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:36:50',
                'updated_at' => '2019-10-07 06:36:50',
            ),
            69 => 
            array (
                'id' => 70,
                'service_id' => 4,
                'benefit_id' => 15,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:37:09',
                'updated_at' => '2019-10-07 06:37:09',
            ),
            70 => 
            array (
                'id' => 71,
                'service_id' => 5,
                'benefit_id' => 15,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:37:34',
                'updated_at' => '2019-10-07 06:37:34',
            ),
            71 => 
            array (
                'id' => 72,
                'service_id' => 6,
                'benefit_id' => 15,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:37:47',
                'updated_at' => '2019-10-07 06:37:47',
            ),
            72 => 
            array (
                'id' => 73,
                'service_id' => 8,
                'benefit_id' => 15,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:38:02',
                'updated_at' => '2019-10-07 06:38:02',
            ),
            73 => 
            array (
                'id' => 74,
                'service_id' => 7,
                'benefit_id' => 15,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:38:39',
                'updated_at' => '2019-10-07 06:38:39',
            ),
            74 => 
            array (
                'id' => 75,
                'service_id' => 8,
                'benefit_id' => 13,
                'note' => '$40.30',
                'note_cn' => '$40.30',
                'note_vi' => '$40.30',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:39:50',
                'updated_at' => '2019-10-07 06:39:50',
            ),
            75 => 
            array (
                'id' => 76,
                'service_id' => 4,
                'benefit_id' => 16,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:40:22',
                'updated_at' => '2019-10-07 06:40:22',
            ),
            76 => 
            array (
                'id' => 77,
                'service_id' => 5,
                'benefit_id' => 16,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:42:54',
                'updated_at' => '2019-10-07 06:42:54',
            ),
            77 => 
            array (
                'id' => 78,
                'service_id' => 6,
                'benefit_id' => 16,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:43:10',
                'updated_at' => '2019-10-07 06:43:10',
            ),
            78 => 
            array (
                'id' => 79,
                'service_id' => 7,
                'benefit_id' => 16,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:44:58',
                'updated_at' => '2019-10-07 06:44:58',
            ),
            79 => 
            array (
                'id' => 80,
                'service_id' => 8,
                'benefit_id' => 16,
                'note' => '12 months',
                'note_cn' => '12 months',
                'note_vi' => '12 months',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:45:34',
                'updated_at' => '2019-10-07 06:45:34',
            ),
            80 => 
            array (
                'id' => 81,
                'service_id' => 4,
                'benefit_id' => 17,
                'note' => '3 minimum months cover period',
                'note_cn' => '3 minimum months cover period',
                'note_vi' => '3 minimum months cover period',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:47:04',
                'updated_at' => '2019-10-07 06:54:27',
            ),
            81 => 
            array (
                'id' => 82,
                'service_id' => 5,
                'benefit_id' => 17,
                'note' => 'No fee',
                'note_cn' => 'No fee',
                'note_vi' => 'No fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:47:21',
                'updated_at' => '2019-10-07 06:47:21',
            ),
            82 => 
            array (
                'id' => 83,
                'service_id' => 6,
                'benefit_id' => 17,
                'note' => 'No fee',
                'note_cn' => 'No fee',
                'note_vi' => 'No fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:49:36',
                'updated_at' => '2019-10-07 06:49:36',
            ),
            83 => 
            array (
                'id' => 84,
                'service_id' => 7,
                'benefit_id' => 17,
                'note' => 'No fee',
                'note_cn' => 'No fee',
                'note_vi' => 'No fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:50:21',
                'updated_at' => '2019-10-07 06:50:21',
            ),
            84 => 
            array (
                'id' => 85,
                'service_id' => 8,
                'benefit_id' => 17,
                'note' => 'No fee',
                'note_cn' => 'No fee',
                'note_vi' => 'No fee',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:51:37',
                'updated_at' => '2019-10-07 06:51:37',
            ),
            85 => 
            array (
                'id' => 86,
                'service_id' => 4,
                'benefit_id' => 18,
            'note' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
            'note_cn' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
            'note_vi' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:55:30',
                'updated_at' => '2019-10-07 07:37:10',
            ),
            86 => 
            array (
                'id' => 87,
                'service_id' => 5,
                'benefit_id' => 18,
            'note' => '134 148 within Australia </br> +61 3 9862 1095 (Calling from outside of Australia) </br> Monday to Friday 8.30am - 6.30pm AEST',
            'note_cn' => '134 148 within Australia </br> +61 3 9862 1095 (Calling from outside of Australia) </br> Monday to Friday 8.30am - 6.30pm AEST',
            'note_vi' => '134 148 within Australia </br> +61 3 9862 1095 (Calling from outside of Australia) </br> Monday to Friday 8.30am - 6.30pm AEST',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:55:53',
                'updated_at' => '2019-10-07 07:38:41',
            ),
            87 => 
            array (
                'id' => 88,
                'service_id' => 8,
                'benefit_id' => 18,
            'note' => '1800 888 942 (within Australia) </br> 61 3 9937 4223 (Calling from outside Australia)',
            'note_cn' => '1800 888 942 (within Australia) </br> 61 3 9937 4223 (Calling from outside Australia)',
            'note_vi' => '1800 888 942 (within Australia) </br> 61 3 9937 4223 (Calling from outside Australia)',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:56:34',
                'updated_at' => '2019-10-07 07:39:35',
            ),
            88 => 
            array (
                'id' => 89,
                'service_id' => 7,
                'benefit_id' => 18,
                'note' => '1800 775 204',
                'note_cn' => '1800 775 204',
                'note_vi' => '1800 775 204',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:56:54',
                'updated_at' => '2019-10-07 06:56:54',
            ),
            89 => 
            array (
                'id' => 90,
                'service_id' => 6,
                'benefit_id' => 19,
                'note' => '1800 006 745',
                'note_cn' => '1800 006 745',
                'note_vi' => '1800 006 745',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:57:21',
                'updated_at' => '2019-10-07 06:57:21',
            ),
            90 => 
            array (
                'id' => 91,
                'service_id' => 5,
                'benefit_id' => 19,
                'note' => '1800 006 745',
                'note_cn' => '1800 006 745',
                'note_vi' => '1800 006 745',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:57:40',
                'updated_at' => '2019-10-07 06:57:40',
            ),
            91 => 
            array (
                'id' => 92,
                'service_id' => 4,
                'benefit_id' => 19,
                'note' => '1800 814 781',
                'note_cn' => '1800 814 781',
                'note_vi' => '1800 814 781',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:58:18',
                'updated_at' => '2019-10-07 06:58:18',
            ),
            92 => 
            array (
                'id' => 93,
                'service_id' => 8,
                'benefit_id' => 19,
                'note' => '+ 61 3 9937 3999',
                'note_cn' => '+ 61 3 9937 3999',
                'note_vi' => '+ 61 3 9937 3999',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:58:37',
                'updated_at' => '2019-10-07 06:58:37',
            ),
            93 => 
            array (
                'id' => 94,
                'service_id' => 7,
                'benefit_id' => 19,
                'note' => '1800 022 222',
                'note_cn' => '1800 022 222',
                'note_vi' => '1800 022 222',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:58:54',
                'updated_at' => '2019-10-07 06:58:54',
            ),
            94 => 
            array (
                'id' => 95,
                'service_id' => 6,
                'benefit_id' => 20,
                'note' => 'AHM OSHC',
                'note_cn' => 'AHM OSHC',
                'note_vi' => 'AHM OSHC',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:59:31',
                'updated_at' => '2020-09-25 18:19:54',
            ),
            95 => 
            array (
                'id' => 96,
                'service_id' => 4,
                'benefit_id' => 20,
                'note' => 'My OSHC Assistant',
                'note_cn' => 'My OSHC Assistant',
                'note_vi' => 'My OSHC Assistant',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 06:59:58',
                'updated_at' => '2019-10-07 06:59:58',
            ),
            96 => 
            array (
                'id' => 97,
                'service_id' => 5,
                'benefit_id' => 20,
                'note' => 'MEDIBANK OSHC',
                'note_cn' => 'MEDIBANK OSHC',
                'note_vi' => 'MEDIBANK OSHC',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:00:15',
                'updated_at' => '2020-09-25 18:20:31',
            ),
            97 => 
            array (
                'id' => 98,
                'service_id' => 6,
                'benefit_id' => 18,
            'note' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
            'note_cn' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
            'note_vi' => '13 6742 within Australia </br> +61 7 3305 8841 (Calling from outside Australia)',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:00:52',
                'updated_at' => '2019-10-07 07:40:56',
            ),
            98 => 
            array (
                'id' => 99,
                'service_id' => 8,
                'benefit_id' => 20,
                'note' => 'myBUPA',
                'note_cn' => 'myBUPA',
                'note_vi' => 'myBUPA',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:03:24',
                'updated_at' => '2020-09-25 18:44:50',
            ),
            99 => 
            array (
                'id' => 100,
                'service_id' => 7,
                'benefit_id' => 20,
                'note' => 'nib Health Insurance',
                'note_cn' => 'nib Health Insurance',
                'note_vi' => 'nib Health Insurance',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:03:37',
                'updated_at' => '2020-09-25 18:42:06',
            ),
            100 => 
            array (
                'id' => 101,
                'service_id' => 4,
                'benefit_id' => 21,
                'note' => 'Sonder',
                'note_cn' => 'Sonder',
                'note_vi' => 'Sonder',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:04:02',
                'updated_at' => '2019-10-07 07:04:02',
            ),
            101 => 
            array (
                'id' => 102,
                'service_id' => 5,
                'benefit_id' => 21,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:04:18',
                'updated_at' => '2019-10-07 07:04:18',
            ),
            102 => 
            array (
                'id' => 103,
                'service_id' => 6,
                'benefit_id' => 21,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:04:38',
                'updated_at' => '2019-10-07 07:04:38',
            ),
            103 => 
            array (
                'id' => 104,
                'service_id' => 8,
                'benefit_id' => 21,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:04:48',
                'updated_at' => '2019-10-07 07:04:48',
            ),
            104 => 
            array (
                'id' => 105,
                'service_id' => 7,
                'benefit_id' => 21,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:04:58',
                'updated_at' => '2019-10-07 07:04:58',
            ),
            105 => 
            array (
                'id' => 106,
                'service_id' => 4,
                'benefit_id' => 22,
                'note' => 'Via “Doctor on demand app”',
                'note_cn' => 'Via “Doctor on demand app”',
                'note_vi' => 'Via “Doctor on demand app”',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:05:42',
                'updated_at' => '2019-10-07 07:05:42',
            ),
            106 => 
            array (
                'id' => 107,
                'service_id' => 5,
                'benefit_id' => 22,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:05:55',
                'updated_at' => '2019-10-07 07:05:55',
            ),
            107 => 
            array (
                'id' => 108,
                'service_id' => 6,
                'benefit_id' => 22,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:06:07',
                'updated_at' => '2019-10-07 07:06:07',
            ),
            108 => 
            array (
                'id' => 109,
                'service_id' => 7,
                'benefit_id' => 22,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:06:16',
                'updated_at' => '2019-10-07 07:06:16',
            ),
            109 => 
            array (
                'id' => 110,
                'service_id' => 8,
                'benefit_id' => 22,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2019-10-07 07:06:28',
                'updated_at' => '2019-10-07 07:06:28',
            ),
            110 => 
            array (
                'id' => 111,
                'service_id' => 4,
                'benefit_id' => 23,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 17:54:15',
                'updated_at' => '2020-09-25 17:54:15',
            ),
            111 => 
            array (
                'id' => 112,
                'service_id' => 5,
                'benefit_id' => 23,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 17:54:34',
                'updated_at' => '2020-09-25 17:54:34',
            ),
            112 => 
            array (
                'id' => 113,
                'service_id' => 6,
                'benefit_id' => 23,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 17:54:43',
                'updated_at' => '2020-09-25 17:54:43',
            ),
            113 => 
            array (
                'id' => 114,
                'service_id' => 7,
                'benefit_id' => 23,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 17:54:56',
                'updated_at' => '2020-09-25 17:54:56',
            ),
            114 => 
            array (
                'id' => 115,
                'service_id' => 8,
                'benefit_id' => 23,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 17:55:08',
                'updated_at' => '2020-09-25 17:55:08',
            ),
            115 => 
            array (
                'id' => 116,
                'service_id' => 6,
                'benefit_id' => 24,
                'note' => 'Sharing network with Medibank',
                'note_cn' => 'Sharing network with Medibank',
                'note_vi' => 'Sharing network with Medibank',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:08:17',
                'updated_at' => '2020-09-25 18:08:17',
            ),
            116 => 
            array (
                'id' => 117,
                'service_id' => 5,
                'benefit_id' => 24,
                'note' => 'Medium',
                'note_cn' => 'Medium',
                'note_vi' => 'Medium',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:09:37',
                'updated_at' => '2020-09-25 18:09:37',
            ),
            117 => 
            array (
                'id' => 118,
                'service_id' => 4,
                'benefit_id' => 24,
                'note' => 'Biggest',
                'note_cn' => 'Biggest',
                'note_vi' => 'Biggest',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:09:55',
                'updated_at' => '2020-09-25 18:09:55',
            ),
            118 => 
            array (
                'id' => 119,
                'service_id' => 7,
                'benefit_id' => 24,
                'note' => 'Low',
                'note_cn' => 'Low',
                'note_vi' => 'Low',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:10:18',
                'updated_at' => '2020-09-25 18:32:42',
            ),
            119 => 
            array (
                'id' => 120,
                'service_id' => 6,
                'benefit_id' => 25,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:12:32',
                'updated_at' => '2020-09-25 18:12:32',
            ),
            120 => 
            array (
                'id' => 121,
                'service_id' => 5,
                'benefit_id' => 25,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:13:02',
                'updated_at' => '2020-09-25 18:13:02',
            ),
            121 => 
            array (
                'id' => 122,
                'service_id' => 4,
                'benefit_id' => 25,
                'note' => NULL,
                'note_cn' => NULL,
                'note_vi' => NULL,
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:13:13',
                'updated_at' => '2020-09-25 18:13:13',
            ),
            122 => 
            array (
                'id' => 123,
                'service_id' => 7,
                'benefit_id' => 25,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:13:27',
                'updated_at' => '2020-09-25 18:14:05',
            ),
            123 => 
            array (
                'id' => 124,
                'service_id' => 8,
                'benefit_id' => 25,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:13:48',
                'updated_at' => '2020-09-25 18:13:48',
            ),
            124 => 
            array (
                'id' => 125,
                'service_id' => 4,
                'benefit_id' => 26,
                'note' => '13SICK National Home Doctor',
                'note_cn' => '13SICK National Home Doctor',
                'note_vi' => '13SICK National Home Doctor',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:16:45',
                'updated_at' => '2020-09-25 18:16:45',
            ),
            125 => 
            array (
                'id' => 126,
                'service_id' => 5,
                'benefit_id' => 26,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:17:22',
                'updated_at' => '2020-09-25 18:17:22',
            ),
            126 => 
            array (
                'id' => 127,
                'service_id' => 6,
                'benefit_id' => 26,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:17:32',
                'updated_at' => '2020-09-25 18:17:32',
            ),
            127 => 
            array (
                'id' => 128,
                'service_id' => 7,
                'benefit_id' => 26,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:17:47',
                'updated_at' => '2020-09-25 18:17:47',
            ),
            128 => 
            array (
                'id' => 129,
                'service_id' => 8,
                'benefit_id' => 26,
                'note' => 'x',
                'note_cn' => 'x',
                'note_vi' => 'x',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:17:57',
                'updated_at' => '2020-09-25 18:17:57',
            ),
            129 => 
            array (
                'id' => 130,
                'service_id' => 8,
                'benefit_id' => 24,
                'note' => 'Medium',
                'note_cn' => 'Medium',
                'note_vi' => 'Medium',
                'created_by' => 1,
                'status' => 1,
                'created_at' => '2020-09-25 18:33:19',
                'updated_at' => '2020-09-25 18:33:19',
            ),
        ));
        
        
    }
}