<?php

use Illuminate\Database\Seeder;

class WebinfosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('webinfos')->delete();
        
        \DB::table('webinfos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'logo',
                'name' => 'Logo',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/logo.png',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 02:08:34',
                'updated_at' => '2019-08-03 02:08:34',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'link_fb',
                'name' => 'Link Facebook',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 02:12:43',
                'updated_at' => '2019-08-03 02:12:43',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'link_twiter',
                'name' => 'Link Twiter',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 02:13:15',
                'updated_at' => '2019-08-03 02:13:15',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'link_gplus',
                'name' => 'Link GooglePlus',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 02:13:42',
                'updated_at' => '2019-08-03 02:13:42',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'hotline',
                'name' => 'Hotline',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => '0999.999.999',
                'status' => 0,
                'created_at' => '2019-08-03 02:14:23',
                'updated_at' => '2020-10-05 18:05:14',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'quote_now',
                'name' => 'Quote OSHC now',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 02:15:23',
                'updated_at' => '2019-08-03 02:15:23',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'special_offer',
                'name' => 'Special Offer',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'http://oshcglobal.com.au/special-offer.html',
                'content' => NULL,
                'status' => 0,
                'created_at' => '2019-08-03 02:16:06',
                'updated_at' => '2020-09-18 20:47:07',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'copyright',
                'name' => 'Copyright',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => 'Copyright 2019 © OSHCGLOBAL All Rights Reseved. ABN 26 609 001 185.',
                'content_vi' => 'Copyright 2019 © OSHCGLOBAL All Rights Reseved. ABN 26 609 001 185.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Copyright 2019 © OSHCGLOBAL All Rights Reseved. ABN 26 609 001 185.',
                'status' => 1,
                'created_at' => '2019-08-03 02:17:10',
                'updated_at' => '2020-09-11 16:30:40',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'title_form_home',
                'name' => 'Compare & Choose Best OSHC',
                'name_cn' => '比较所有供应商',
                'name_vi' => 'So sánh mọi lựa chọn của bạn',
                'content_cn' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'content_vi' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'image' => NULL,
                'link' => 'http://oshcglobal.com.au/get-a-quote',
                'content' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'status' => 1,
                'created_at' => '2019-08-03 03:05:31',
                'updated_at' => '2020-09-21 17:39:17',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'des_form_home',
                'name' => 'Mô tả form trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:06:15',
                'updated_at' => '2020-08-29 12:23:00',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'banner_home',
                'name' => 'Banner trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '<span>为你做一切都很容易</span>
<strong>OSHC一站式服务</strong>',
                'content_vi' => '<span>TÌM KIẾM MỌI THỨ DỄ DÀNG CHO BẠN</span>
<strong>OSHC One- Stop-Shop</strong>',
                'image' => NULL,
                'link' => NULL,
                'content' => '<span>MAKE EVERYTHING EASY FOR YOU</span>
<strong>OSHC One- Stop-Shop</strong>',
                'status' => 1,
                'created_at' => '2019-08-03 03:10:32',
                'updated_at' => '2019-08-19 03:14:56',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'sevice_title_home',
                'name' => 'We are here to help you',
                'name_cn' => 'We are here to help you',
                'name_vi' => 'We are here to help you',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:14:21',
                'updated_at' => '2020-09-23 13:57:21',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'sevice_des_home',
                'name' => 'Mô tả dịch vụ trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:15:02',
                'updated_at' => '2020-09-21 17:41:45',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'sevice_intro_home_1',
                'name' => 'Giới thiệu dịch vụ trang chủ 1',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '相比 ＆
报价并购买',
                'content_vi' => 'So sánh &
Xem và mua',
                'image' => 'FILES/source/sv1.png',
                'link' => '#',
                'content' => 'Compare & 
Quote and buy',
                'status' => 1,
                'created_at' => '2019-08-03 03:27:14',
                'updated_at' => '2019-08-19 03:34:53',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'sevice_intro_home_2',
                'name' => 'Giới thiệu dịch vụ trang chủ 2',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '延伸',
                'content_vi' => 'MỞ RỘNG',
                'image' => 'FILES/source/sv2.png',
                'link' => '#',
                'content' => 'Extend',
                'status' => 1,
                'created_at' => '2019-08-03 03:27:44',
                'updated_at' => '2019-08-19 03:35:45',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'sevice_intro_home_3',
                'name' => 'Giới thiệu dịch vụ trang chủ 3',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '升级',
                'content_vi' => 'NÂNG CẤP',
                'image' => 'FILES/source/sv3.png',
                'link' => '#',
                'content' => 'Upgrade',
                'status' => 1,
                'created_at' => '2019-08-03 03:27:55',
                'updated_at' => '2019-08-19 03:36:43',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'sevice_intro_home_4',
                'name' => 'Giới thiệu dịch vụ trang chủ 4',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '交换盖',
                'content_vi' => 'TRAO ĐỔI',
                'image' => 'FILES/source/sv4.png',
                'link' => '#',
                'content' => 'Exchange cover',
                'status' => 1,
                'created_at' => '2019-08-03 03:29:12',
                'updated_at' => '2019-08-19 03:38:04',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'sevice_home_1',
                'name' => 'OSHC policy',
                'name_cn' => 'OSHC政策',
                'name_vi' => 'Chính sách OSHC',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/i1.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:32:45',
                'updated_at' => '2020-08-29 12:56:48',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'sevice_home_2',
                'name' => 'ACTIVATE OSHC',
                'name_cn' => '激活OSHC',
                'name_vi' => 'HOẠT ĐỘNG OSHC',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/i2.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:33:37',
                'updated_at' => '2020-08-29 12:57:09',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'sevice_home_3',
                'name' => 'FIND A DOCTOR',
                'name_cn' => '寻找医生',
                'name_vi' => 'TÌM KIẾM',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/i3.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:34:24',
                'updated_at' => '2020-08-29 13:00:10',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'sevice_home_4',
                'name' => 'CLAIM',
                'name_cn' => '要求',
                'name_vi' => 'YÊU CẦU',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/i4.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:34:54',
                'updated_at' => '2020-08-29 12:55:20',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'sevice_home_5',
                'name' => 'Refund',
                'name_cn' => '退',
                'name_vi' => 'Hoàn tiền',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/i4.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:35:24',
                'updated_at' => '2020-08-29 12:56:17',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'sevice_home_6',
                'name' => 'Q & A',
                'name_cn' => '问答',
                'name_vi' => 'Hỏi đáp',
                'content_cn' => '您是否知道您可以选择海外学生健康保险（OSHC）提供者？',
            'content_vi' => 'Bạn có biết bạn có sự lựa chọn nhà cung cấp Bảo hiểm Sức khỏe Sinh viên Nước ngoài (OSHC) không?',
                'image' => 'FILES/source/i6.png',
                'link' => 'http://oshcglobal.com.au/qa',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:36:07',
                'updated_at' => '2020-07-24 07:40:41',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'title_choose_home',
                'name' => 'Why Choose Us?',
                'name_cn' => '为什么选择我们？',
                'name_vi' => 'Tại sao chọn chúng tôi?',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:40:51',
                'updated_at' => '2020-09-11 19:36:11',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'des_choose_home',
                'name' => 'Mô tả lý do lựa chọn trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 03:42:49',
                'updated_at' => '2020-09-21 17:42:01',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'chose_home_1',
                'name' => 'One click to compare &',
                'name_cn' => '点击一下即可比较',
                'name_vi' => 'Một cú nhấp chuột để so sánh',
                'content_cn' => '选择合适的OSHC',
                'content_vi' => 'chọn một OSHC phù hợp',
                'image' => 'FILES/source/ld1.png',
                'link' => NULL,
                'content' => 'choose a suitable OSHC',
                'status' => 1,
                'created_at' => '2019-08-03 03:56:50',
                'updated_at' => '2019-08-19 04:01:34',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'chose_home_2',
                'name' => 'Have your policy',
                'name_cn' => '有你的政策',
                'name_vi' => 'Có chính sách của bạn',
                'content_cn' => '在几分钟内',
                'content_vi' => 'trong vài phút',
                'image' => 'FILES/source/ld2.png',
                'link' => NULL,
                'content' => 'in minutes',
                'status' => 1,
                'created_at' => '2019-08-03 03:58:12',
                'updated_at' => '2019-08-19 04:03:52',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'chose_home_3',
                'name' => 'Exclusive offer',
                'name_cn' => '独家提供',
                'name_vi' => 'Ưu đãi độc quyền',
                'content_cn' => '独家储蓄',
                'content_vi' => 'tiết kiệm độc quyền',
                'image' => 'FILES/source/ld3.png',
                'link' => NULL,
                'content' => 'exclusive savings',
                'status' => 1,
                'created_at' => '2019-08-03 03:59:20',
                'updated_at' => '2019-08-19 04:05:18',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'chose_home_4',
                'name' => 'Provide all infomation',
                'name_cn' => '提供所有信息',
                'name_vi' => 'Cung cấp tất cả thông tin',
                'content_cn' => '在一个站',
                'content_vi' => 'trong một trạm',
                'image' => 'FILES/source/ld4.png',
                'link' => NULL,
                'content' => 'in one station',
                'status' => 1,
                'created_at' => '2019-08-03 04:00:47',
                'updated_at' => '2019-08-19 04:07:06',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'chose_home_5',
                'name' => 'Handle every problem',
                'name_cn' => '处理每一个问题',
                'name_vi' => 'Xử lý mọi vấn đề',
                'content_cn' => '直接最快',
                'content_vi' => 'trực tiếp nhanh nhất',
                'image' => 'FILES/source/ld5.png',
                'link' => NULL,
                'content' => 'directly fastest',
                'status' => 1,
                'created_at' => '2019-08-03 04:02:14',
                'updated_at' => '2019-08-19 04:08:20',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'video_home',
                'name' => 'Video trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => 'https://www.youtube.com/embed/pmkyNgIidgk',
                'content_vi' => 'https://www.youtube.com/embed/pmkyNgIidgk',
                'image' => NULL,
                'link' => NULL,
                'content' => 'https://www.youtube.com/embed/pmkyNgIidgk',
                'status' => 1,
                'created_at' => '2019-08-03 04:03:08',
                'updated_at' => '2019-09-25 02:43:54',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'title_client_home',
                'name' => 'Tiêu đề khách hàng trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => 'What Are Our Clients Saying ?',
                'status' => 1,
                'created_at' => '2019-08-03 04:08:55',
                'updated_at' => '2019-08-03 04:08:55',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'des_client_home',
                'name' => 'Mô tả khách hàng trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 07:04:11',
                'updated_at' => '2020-07-24 07:44:02',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'partner_title_home',
                'name' => 'Our Partners',
                'name_cn' => '我们的伙伴',
                'name_vi' => 'Đối tác của chúng tôi',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:06:11',
                'updated_at' => '2020-09-11 19:36:42',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'partner_des_home',
                'name' => 'Mô tả đối tác trang chủ',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:06:51',
                'updated_at' => '2020-09-21 17:40:05',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'pt_item_1',
                'name' => 'Allianz',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
            'image' => 'FILES/source/oshc-allianz%20(1).png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:07:43',
                'updated_at' => '2020-09-11 17:59:29',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'pt_item_2',
                'name' => 'AHM',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
            'image' => 'FILES/source/ahm-oshc%20(1).jpg',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:08:06',
                'updated_at' => '2020-09-11 17:59:11',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'pt_item_3',
                'name' => 'Bupa',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
            'image' => 'FILES/source/oshc-bupa%20(1).png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:08:22',
                'updated_at' => '2020-09-11 17:59:44',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'pt_item_4',
                'name' => 'Medibank',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/Medibank%20logo.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:08:42',
                'updated_at' => '2020-09-11 18:24:50',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'pt_item_5',
                'name' => 'NIB',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
            'image' => 'FILES/source/oshc-nib%20(1).jpg',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-03 08:09:00',
                'updated_at' => '2020-09-11 18:00:18',
            ),
            40 => 
            array (
                'id' => 43,
                'code' => 'title_footer_col_1',
                'name' => 'About Us',
                'name_cn' => '关于我们',
                'name_vi' => 'Về chúng tôi',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => 'Australia Business Number: 26 609 001 185',
                'status' => 1,
                'created_at' => '2019-08-05 02:09:23',
                'updated_at' => '2020-09-11 12:18:08',
            ),
            41 => 
            array (
                'id' => 44,
                'code' => 'title_footer_col_2',
                'name' => 'Terms & Conditions',
                'name_cn' => 'Terms & Conditions',
                'name_vi' => 'Terms & Conditions',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-05 02:09:53',
                'updated_at' => '2020-09-04 14:59:48',
            ),
            42 => 
            array (
                'id' => 45,
                'code' => 'title_footer_col_3',
                'name' => 'Privacy Policy',
                'name_cn' => '政策',
                'name_vi' => 'Chính sách',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'https://oshcglobal.com.au/news/policy/privacy-policy.html',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-05 02:10:51',
                'updated_at' => '2020-10-07 14:58:36',
            ),
            43 => 
            array (
                'id' => 46,
                'code' => 'content_footer_col_1',
                'name' => 'Nội dung chân trang cột 1',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => '<p>OSHCGlobal ABN: 26 609 001 185 </p>',
                'status' => 1,
                'created_at' => '2019-08-05 02:11:55',
                'updated_at' => '2020-09-13 18:39:05',
            ),
            44 => 
            array (
                'id' => 47,
                'code' => 'content_footer_col_2',
                'name' => 'Nội dung chân trang cột 2',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => '<ul>
<li>OSHCGlobal</li>
<li>ABN: 26 609 001 185</li>
</ul>',
                'status' => 1,
                'created_at' => '2019-08-05 02:12:21',
                'updated_at' => '2020-09-13 18:40:41',
            ),
            45 => 
            array (
                'id' => 48,
                'code' => 'content_footer_col_3',
                'name' => 'Nội dung chân trang cột 3',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => '<ul>
<li><a href="">Warranty Policy</a></li>
<li><a href="">Shipping policy</a></li>
<li><a href="">Policy for returning goods</a></li>
<li><a href="">Information security policy</a></li>
<li><a href="">Payment Guide</a></li>
</ul>',
                'status' => 1,
                'created_at' => '2019-08-05 02:12:55',
                'updated_at' => '2019-08-05 02:12:55',
            ),
            46 => 
            array (
                'id' => 49,
                'code' => 'get_a_quote_section_1',
                'name' => 'Register with our services',
                'name_cn' => '注册我们的服务',
                'name_vi' => 'Đăng ký với dịch vụ của chúng tôi',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-19 04:31:38',
                'updated_at' => '2020-07-24 08:15:04',
            ),
            47 => 
            array (
                'id' => 50,
                'code' => 'get_a_quote_section_2',
            'name' => 'How to calculate the start date and the end date of visa(?)',
                'name_cn' => '如何计算签证的开始日期和结束日期（？）',
            'name_vi' => 'Cách tính ngày bắt đầu và ngày kết thúc visa (?)',
            'content_cn' => '<p>Your policy must start from the date you’ll arrive in Australia, or the date that any previous policy ends (or is cancelled).</p>
<p>
Your policy must cover until at least the end of your student visa.</><p>
</>Note: If you hold a student dependent visa, you must be insured under the same policy as the main student visa holder. You are only eligible to hold a single OSHC policy if you are the primary visa holder.<p>',
            'content_vi' => '<p>Your policy must start from the date you’ll arrive in Australia, or the date that any previous policy ends (or is cancelled).</p>
<p>
Your policy must cover until at least the end of your student visa.</><p>
</>Note: If you hold a student dependent visa, you must be insured under the same policy as the main student visa holder. You are only eligible to hold a single OSHC policy if you are the primary visa holder.<p>',
                'image' => NULL,
                'link' => '#',
            'content' => '<p>Your policy must start from the date you’ll arrive in Australia, or the date that any previous policy ends (or is cancelled).</p>
<p>
Your policy must cover until at least the end of your student visa.</><p>',
                'status' => 1,
                'created_at' => '2019-08-19 07:16:28',
                'updated_at' => '2020-09-21 20:17:36',
            ),
            48 => 
            array (
                'id' => 51,
                'code' => 'get_a_quote_banner_deskop_1',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/banner-oshcglobal-quote.png',
                'link' => 'https://oshcstudents.com.au/buy-allianz-oshc-get-a-chance-to-win-up-to-au2000-with-annalink-oshcstudents/',
                'content' => NULL,
                'status' => 0,
                'created_at' => '2019-08-19 07:58:22',
                'updated_at' => '2020-09-18 17:28:54',
            ),
            49 => 
            array (
                'id' => 52,
                'code' => 'apply_section_1',
                'name' => 'Register with our services',
                'name_cn' => '注册我们的服务',
                'name_vi' => 'Đăng ký với dịch vụ của chúng tôi',
                'content_cn' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'content_vi' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'status' => 1,
                'created_at' => '2019-08-19 09:54:30',
                'updated_at' => '2020-09-21 17:41:23',
            ),
            50 => 
            array (
                'id' => 53,
                'code' => 'apply_section_2',
                'name' => 'Personal Details',
                'name_cn' => '个人资料',
                'name_vi' => 'Thông tin cá nhân',
                'content_cn' => '请确保您的电子邮件地址是正确的，因为您的证书和会员卡将发送到您的以下电子邮箱。',
                'content_vi' => 'Vui lòng đảm bảo địa chỉ email của bạn là đúng vì chứng chỉ và thẻ thành viên của bạn sẽ được gửi đến email bên dưới của bạn.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Please make sure your email address is the right one because your certificate and membership card will be sent to your below email.',
                'status' => 1,
                'created_at' => '2019-08-19 10:36:23',
                'updated_at' => '2019-08-19 10:36:23',
            ),
            51 => 
            array (
                'id' => 54,
                'code' => 'apply_section_3',
                'name' => 'Is the primary student visa holder currently located in Australia?',
                'name_cn' => '主要学生签证持有人目前是否位于澳大利亚？',
                'name_vi' => 'Bạn có visa ở Úc',
                'content_cn' => '主要学生签证持有人目前是否位于澳大利亚？',
                'content_vi' => 'Bạn có visa ở Úc',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Is the primary student visa holder currently located in Australia?',
                'status' => 1,
                'created_at' => '2019-08-22 02:31:26',
                'updated_at' => '2019-08-22 07:36:32',
            ),
            52 => 
            array (
                'id' => 55,
                'code' => 'apply_section_4',
                'name' => 'banner',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/banner-reg.jpg',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-22 07:33:44',
                'updated_at' => '2019-08-22 07:33:44',
            ),
            53 => 
            array (
                'id' => 56,
                'code' => 'apply_section_5',
                'name' => 'Terms and conditions',
                'name_cn' => '条款和条件',
                'name_vi' => 'Điều khoản và điều kiện',
                'content_cn' => '以及政策措辞',
                'content_vi' => 'cũng như từ ngữ chính sách',
                'image' => NULL,
                'link' => '#',
                'content' => 'as well as the Policy Wording',
                'status' => 1,
                'created_at' => '2019-08-22 07:42:36',
                'updated_at' => '2019-08-22 07:42:36',
            ),
            54 => 
            array (
                'id' => 57,
                'code' => 'apply_section_6',
                'name' => 'I confirm that the information',
                'name_cn' => 'I confirm that the information',
                'name_vi' => 'I confirm that the information',
                'content_cn' => '我确认此表格中提供的信息真实，完整和准确',
                'content_vi' => 'Tôi xác nhận rằng thông tin được cung cấp trong mẫu này là đúng, đầy đủ và chính xác.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'I confirm that the information given in this form is true, complete and accurate.',
                'status' => 1,
                'created_at' => '2019-08-22 07:46:17',
                'updated_at' => '2019-08-22 07:46:17',
            ),
            55 => 
            array (
                'id' => 58,
                'code' => 'payment_section_1',
                'name' => 'Register with our services',
                'name_cn' => '注册我们的服务',
                'name_vi' => 'Đăng ký với dịch vụ của chúng tôi',
                'content_cn' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'content_vi' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Compare & choose OSHC cover that suits your needs, save you up to thousands of dollars',
                'status' => 1,
                'created_at' => '2019-08-27 03:11:17',
                'updated_at' => '2020-09-21 17:40:24',
            ),
            56 => 
            array (
                'id' => 59,
                'code' => 'payment_section_2',
                'name' => 'Pls choose your',
                'name_cn' => 'Pls choose your',
                'name_vi' => 'Pls choose your',
                'content_cn' => '请选择您的首选付款方式，无论您来自哪个国家/地区:',
                'content_vi' => 'Vui lòng chọn phương thức thanh toán ưa thích của bạn, bất kể bạn đến từ quốc gia nào:',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Pls choose your preferred payment method, no matter what country you are from:',
                'status' => 1,
                'created_at' => '2019-08-27 03:21:26',
                'updated_at' => '2019-08-27 03:21:26',
            ),
            57 => 
            array (
                'id' => 60,
                'code' => 'payment_section_3',
                'name' => 'payment method 1',
                'name_cn' => 'payment method 1',
                'name_vi' => 'payment method 1',
                'content_cn' => '通过电汇支付',
                'content_vi' => 'Thanh toán bằng chuyển khoản điện báo',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Pay by Telegraphic Transfer',
                'status' => 1,
                'created_at' => '2019-08-27 03:25:50',
                'updated_at' => '2019-08-27 03:25:50',
            ),
            58 => 
            array (
                'id' => 61,
                'code' => 'payment_section_4',
                'name' => 'payment method 2',
                'name_cn' => 'payment method 2',
                'name_vi' => 'payment method 2',
                'content_cn' => '通过PayPal付款',
                'content_vi' => 'Thanh toán bằng PayPal',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Pay by PayPal',
                'status' => 1,
                'created_at' => '2019-08-27 03:27:39',
                'updated_at' => '2019-08-27 03:27:39',
            ),
            59 => 
            array (
                'id' => 62,
                'code' => 'payment_section_5',
                'name' => 'payment menthod 3',
                'name_cn' => 'payment menthod 3',
                'name_vi' => 'payment menthod 3',
                'content_cn' => '用信用卡支付',
                'content_vi' => 'Trả bằng thẻ tín dụng',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Pay by Credit Card',
                'status' => 1,
                'created_at' => '2019-08-27 03:28:57',
                'updated_at' => '2019-08-27 03:28:57',
            ),
            60 => 
            array (
                'id' => 63,
                'code' => 'payment_section_6',
            'name' => 'How to pay by Telegraphic (Wire) Transfer',
                'name_cn' => '如何通过电汇（电汇）支付',
                'name_vi' => 'Cách thanh toán bằng chuyển khoản điện báo',
            'content_cn' => '<strong>Telegraphic (Wire) Transfer : </strong> Telegraphic transfers are electronic payments of cleared funds that are credited directly to a nominated bank account. It\'s a fast and reliable way for you to make international payments almost anywhere in the world. Please refer to the following steps.</br>
Step 1: Download the relevant invoice</br>
Step 2: Choose your preferred bank to make the payment.</br>
Please note that all necessary documents such as the invoice, passport photo, offer letter must be provided to the bank.</br>
Step 3: Once completed, please send us the remittance advice at email info@oshcglobal.com</br>
We will issue the certificate as requested once receiving your payment.</br>',
            'content_vi' => '<strong>Telegraphic (Wire) Transfer : </strong> Telegraphic transfers are electronic payments of cleared funds that are credited directly to a nominated bank account. It\'s a fast and reliable way for you to make international payments almost anywhere in the world. Please refer to the following steps.</br>
Step 1: Download the relevant invoice</br>
Step 2: Choose your preferred bank to make the payment.</br>
Please note that all necessary documents such as the invoice, passport photo, offer letter must be provided to the bank.</br>
Step 3: Once completed, please send us the remittance advice at email info@oshcglobal.com</br>
We will issue the certificate as requested once receiving your payment.</br>',
                'image' => NULL,
                'link' => NULL,
            'content' => '<strong>Telegraphic (Wire) Transfer : </strong> Telegraphic transfers are electronic payments of cleared funds that are credited directly to a nominated bank account. It\'s a fast and reliable way for you to make international payments almost anywhere in the world. Please refer to the following steps.</br>
Step 1: Download the relevant invoice</br>
Step 2: Choose your preferred bank to make the payment.</br>
Please note that all necessary documents such as the invoice, passport photo, offer letter must be provided to the bank.</br>
Step 3: Once completed, please send us the remittance advice at email info@oshcglobal.com</br>
We will issue the certificate as requested once receiving your payment.</br>',
                'status' => 1,
                'created_at' => '2019-08-27 03:34:14',
                'updated_at' => '2020-09-13 18:39:55',
            ),
            61 => 
            array (
                'id' => 64,
                'code' => 'payment_section_7',
                'name' => 'image payment',
                'name_cn' => 'image payment',
                'name_vi' => 'image payment',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/listpay.png',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-27 03:47:30',
                'updated_at' => '2019-08-27 03:47:30',
            ),
            62 => 
            array (
                'id' => 65,
                'code' => 'qa_section_1',
                'name' => 'OSHC frequently asked questions',
                'name_cn' => 'OSHC frequently asked questions',
                'name_vi' => 'OSHC frequently asked questions',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-27 07:27:33',
                'updated_at' => '2020-09-13 18:43:15',
            ),
            63 => 
            array (
                'id' => 66,
                'code' => 'qa_section_2',
                'name' => 'Ask us questions',
                'name_cn' => '问我们问题',
                'name_vi' => 'Đặt câu hỏi cho chúng tôi',
                'content_cn' => '发送你的问题',
                'content_vi' => 'GỬI CÂU HỎI CỦA BẠN',
                'image' => NULL,
                'link' => NULL,
                'content' => 'SEND YOUR QUESTIONS',
                'status' => 1,
                'created_at' => '2019-08-27 08:08:56',
                'updated_at' => '2019-08-27 08:16:05',
            ),
            64 => 
            array (
                'id' => 67,
                'code' => 'modal_popup',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => 'QC popup',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/popup-oshcglobal%20-resize.png',
                'link' => 'http://oshcglobal.com.au/get-a-quote',
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-28 10:20:01',
                'updated_at' => '2020-09-30 13:45:50',
            ),
            65 => 
            array (
                'id' => 68,
                'code' => 'news_section_1',
                'name' => 'News OSHCGlobal',
                'name_cn' => 'News OSHCGlobal',
                'name_vi' => 'News OSHCGlobal',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-08-30 03:53:52',
                'updated_at' => '2020-09-13 18:36:36',
            ),
            66 => 
            array (
                'id' => 69,
                'code' => 'reg_section_1',
                'name' => 'Apply to join us',
                'name_cn' => '申请加入我们',
                'name_vi' => 'Đăng ký tham gia với chúng tôi',
                'content_cn' => '我们需要收集一些关于您的事情以启动流程。',
                'content_vi' => 'Chúng tôi cần thu thập một vài điều về bạn để bắt đầu quá trình.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'We need to collect a few things about you to get the process started.',
                'status' => 1,
                'created_at' => '2019-09-04 01:51:10',
                'updated_at' => '2019-09-04 01:51:10',
            ),
            67 => 
            array (
                'id' => 70,
                'code' => 'reg_section_2',
                'name' => 'INFORMATION',
                'name_cn' => '信息',
                'name_vi' => 'THÔNG TIN',
                'content_cn' => '我们需要收集一些关于您的事情以启动流程。',
                'content_vi' => 'Chúng tôi cần thu thập một vài điều về bạn để bắt đầu quá trình.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'We need to collect a few things about you to get the process started.',
                'status' => 1,
                'created_at' => '2019-09-04 01:55:31',
                'updated_at' => '2019-09-04 01:55:31',
            ),
            68 => 
            array (
                'id' => 71,
                'code' => 'reg_section_3',
                'name' => 'Terms & Conditions',
                'name_cn' => '条款和条件',
                'name_vi' => 'Điều khoản và điều kiện',
                'content_cn' => '我确认此表格中提供的信息真实，完整和准确。',
                'content_vi' => 'Tôi xác nhận rằng thông tin được cung cấp trong mẫu này là đúng, đầy đủ và chính xác.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'I confirm that the information given in this form is true, complete and accurate.',
                'status' => 1,
                'created_at' => '2019-09-04 07:14:00',
                'updated_at' => '2019-09-04 07:14:00',
            ),
            69 => 
            array (
                'id' => 72,
                'code' => 'reg_section_4',
                'name' => 'I have read, understood and agreed to the',
                'name_cn' => '我确认此表格中提供的信息真实，完整和准确。',
                'name_vi' => 'Tôi xác nhận rằng thông tin được cung cấp trong mẫu này là đúng, đầy đủ và chính xác.',
                'content_cn' => '条款和条件以及政策措辞',
                'content_vi' => 'Điều khoản và điều kiện cũng như Từ ngữ chính sách',
                'image' => NULL,
                'link' => '#',
                'content' => 'Terms and conditions as well as the Policy Wording',
                'status' => 1,
                'created_at' => '2019-09-04 07:16:02',
                'updated_at' => '2019-09-04 07:20:51',
            ),
            70 => 
            array (
                'id' => 73,
                'code' => 'news_detail_section_1',
                'name' => 'News',
                'name_cn' => 'News',
                'name_vi' => 'News',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-09-09 02:03:59',
                'updated_at' => '2020-09-13 18:37:12',
            ),
            71 => 
            array (
                'id' => 74,
                'code' => 'comment_note',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => '字段是必需的。 请以正确的方式输入您的信息，
在主文本区域留下您的评论文本或回复。',
                'content_vi' => 'Mục này bắt buộc. Vui lòng nhập thông tin của bạn theo đúng cách,
trong khu vực văn bản chính để lại văn bản bình luận của bạn hoặc trả lời.',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Fields are required. Please enter your infomation in the right way, 
in the main text area leave your comment text or reply.',
                'status' => 1,
                'created_at' => '2019-09-11 03:19:27',
                'updated_at' => '2019-09-11 03:19:27',
            ),
            72 => 
            array (
                'id' => 75,
                'code' => 'news_detail_section_2',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/banner.png',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-09-11 03:31:16',
                'updated_at' => '2019-09-11 03:31:16',
            ),
            73 => 
            array (
                'id' => 76,
                'code' => 'news_detail_section_3',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/news_2.png',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-09-11 03:35:11',
                'updated_at' => '2019-09-11 03:35:11',
            ),
            74 => 
            array (
                'id' => 77,
                'code' => 'logo_company',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/oshc%20global%20logo.png',
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => '2019-09-11 09:55:49',
                'updated_at' => '2020-09-11 19:24:29',
            ),
            75 => 
            array (
                'id' => 78,
                'code' => 'payment_finish',
                'name' => 'You have successfully registered the service.',
                'name_cn' => '您已成功注册该服务',
                'name_vi' => 'Bạn đã đăng kí dịch vụ thành công',
                'content_cn' => '请下载发票以完成注册申请',
                'content_vi' => 'Xin vui lòng tải xuống hóa đơn để hoàn thành đăng ký',
                'image' => NULL,
                'link' => NULL,
                'content' => 'Pls download invoice to complete register apply',
                'status' => 1,
                'created_at' => '2019-09-19 07:08:54',
                'updated_at' => '2019-09-19 07:49:34',
            ),
            76 => 
            array (
                'id' => 79,
                'code' => 'email',
                'name' => 'info@oshcglobal.com',
                'name_cn' => NULL,
                'name_vi' => 'email',
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'info@oshcglobal.com',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 14:32:36',
            ),
            77 => 
            array (
                'id' => 80,
                'code' => 'new_letter_footer',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 81,
                'code' => 'about_us',
                'name' => 'About Us',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'https://oshcglobal.com.au/about',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 18:07:27',
            ),
            79 => 
            array (
                'id' => 82,
                'code' => 'term_and_conditions',
                'name' => 'Terms & Conditions',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'https://oshcglobal.com.au/news/terms-conditions/Terms-conditions.html',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 18:09:15',
            ),
            80 => 
            array (
                'id' => 83,
                'code' => 'privacy_policy',
                'name' => 'Privacy Policy',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => 'https://oshcglobal.com.au/news/policy/privacy-policy.html',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-10-07 14:58:17',
            ),
            81 => 
            array (
                'id' => 84,
                'code' => 'address_footer',
                'name' => 'ABN 26 609 001 185',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => NULL,
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-10-05 18:06:04',
            ),
            82 => 
            array (
                'id' => 85,
                'code' => 'home_footer',
                'name' => 'Home',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 86,
                'code' => 'about_footer',
                'name' => 'About',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 87,
                'code' => 'event_footer',
                'name' => 'Event',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 88,
                'code' => 'contact_footer',
                'name' => 'Contact',
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => NULL,
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 89,
                'code' => 'get-a-quote-image-quote-now',
                'name' => NULL,
                'name_cn' => NULL,
                'name_vi' => NULL,
                'content_cn' => NULL,
                'content_vi' => NULL,
                'image' => 'FILES/source/logo.png',
                'link' => '#',
                'content' => NULL,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}