<?php

return [
    'department' => [
        1 => 'Ha Noi',
        2 => 'Ho Chi Minh',
        3 => 'Overseas',
    ],
    'market' => [
        1 => 'Australia',
        2 => 'Canada',
        3 => 'USA',
        4 => 'VietNam',
        5 => 'Nz',
        6 => 'Sing',
        7 => 'UK',
        8 => 'Euroup',
        9 => 'Germany',
        10 => 'France',
        11 => 'Japan',
        12 => 'Taiwan',
        13 => 'Korea',
        14 => 'Asia',
    ],
    'rating' => [
        'A' => 'A',
        'B' => 'B',
        'C' => 'C',
        'D' => 'D',
    ],
    'type_form' => [
        1 => 'Form 1 (OSHC & OVHC & HCC)',
        2 => 'Form 2 (Homestay & APU)',
        3 => 'Form 3 (FLYWIRE)',
        4 => 'Form 3 (STUDY TOUR)',
    ],
    'policy' => [
        1 => 'Single',
        2 => 'Couple',
        3 => 'Family',
        4 => 'Single parent'
    ],
    'status' => [
        1 => 'Active',
        0 => 'Inactive',
    ],
    'donvi' => [
        1 => '%',
        2 => '$',
    ],
    'unit' => [
        1 => 'AUD',
        2 => 'NZD',
        3 => 'USD',
        4 => 'VND',
    ],
    'type_task' => [
        1 => 'Daily',
        2 => 'Weekly',
        3 => 'Monthly',
    ],
    'lv' => [
        1 => 'Low',
        2 => 'Medium',
        3 => 'High',
    ],
    'status_task' => [
        1 => 'Starting',
        2 => 'Processing',
        3 => 'Complete',
    ],
    'contact_by' => [
        1 => 'SMS',
        2 => 'EMAIL',
        3 => 'CALL',
        4 => 'Facebook',
        5 => 'Zalo',
        6 => 'Skype',
        7 => 'Whatapps',
        8 => 'Direct',
    ],
    'service_country' => [
        'A' => 'AU',
        'U' => 'US',
        'N' => 'NZ',
        'V' => 'VN',
        'C' => 'CA'
    ],
    'type_invoice' => [
        1 => 'New',
        2 => 'Extension',
        3 => 'Revise',
        4 => 'Upgrade'
    ],
    'status_invoice' => [
        8 => 'Pending',
        1 => 'Done',
        2 => 'Cancel',
        4 => 'Refund',
        6 => 'Refund - Paid ',
        9 => 'Defer'
    ],
    'type_payment' => [
        1 => 'Monthly',
        2 => 'Deduction com',
    ],
    'status_refund' => [
        1 => 'Done',
        2 => 'Cancel',
        3 => 'Visa',
        4 => 'Refund',
        5 => 'Paid com',
        6 => 'Refund - Paid ',
        7 => 'Hold',
        8 => 'Pending',
    ],
    'status_visa' => [
        1 => 'Granted',
        2 => 'Not yet',
        3 => 'Failed / Cancelled',
        4 => 'Cancel'
    ],
    'type_visa' => [
        1 => '500',
        2 => '600',
        3 => '580',
        4 => '590',
        5 => '485',
        6 => '188',
        7 => 'Briding',
        8 => 'F1',
        9 => '188',
        10 => '300',
        11 => '400',
        12 => '401',
        13 => '402',
        14 => '403',
        15 => '405',
        16 => '407',
        17 => '408',
        18 => '410',
        19 => '416',
        20 => '417',
        21 => '420',
        22 => '457',
        23 => '462',
        24 => '476',
        25 => '482',
        26 => '485',
        27 => '489',
        28 => '590',
        29 => '600',
        30 => '601',
        31 => '602',
        32 => '651',
        33 => '010',
        34 => '020',
        35 => '030',
        36 => 'F1',
    ],
    'bank_fee' => [
        0 => '0%',
        1 => '1%',
        2 => '2%',
        3 => '3%',
        4 => '4%',
        5 => '5%',
        6 => '5 AUD',
        7 => '3,6%',
        8 => '6%'
    ],
    'payment_type' => [
        1 => 'New enrollment',
        2 => 'Current Student',
    ],
    'payment_method' => [
        1 => 'Telegraphic transfer',
        2 => 'Credit card',
        3 => 'Paypal',
        4 => 'Flywire',
    ],
    'su_payment_method' => [
        1 => 0,
        2 => 0.03,
        3 => 0.03,
    ],
    'title' => [
        1 => 'Mr',
        2 => 'Ms',
        3 => 'Mrs',
    ],
    'gender' => [
        1 => 'Male',
        2 => 'Female',
    ],
    'currency' => [
        '',
        'AED',
        'AFN',
        'ALL',
        'AMD',
        'ANG',
        'AOA',
        'ARS',
        'AUD',
        'AWG',
        'AZN',
        'BAM',
        'BBD',
        'BDT',
        'BGN',
        'BHD',
        'BIF',
        'BMD',
        'BND',
        'BOB',
        'BOV',
        'BRL',
        'BSD',
        'BTN',
        'BWP',
        'BYN',
        'BZD',
        'CAD',
        'CDF',
        'CHE',
        'CHF',
        'CHW',
        'CLF',
        'CLP',
        'CNY',
        'COP',
        'COU',
        'CRC',
        'CUC',
        'CUP',
        'CVE',
        'CZK',
        'DJF',
        'DKK',
        'DOP',
        'DZD',
        'EGP',
        'ERN',
        'ETB',
        'EUR',
        'FJD',
        'FKP',
        'GBP',
        'GEL',
        'GHS',
        'GIP',
        'GMD',
        'GNF',
        'GTQ',
        'GYD',
        'HKD',
        'HNL',
        'HRK',
        'HTG',
        'HUF',
        'IDR',
        'ILS',
        'INR',
        'IQD',
        'IRR',
        'ISK',
        'JMD',
        'JOD',
        'JPY',
        'KES',
        'KGS',
        'KHR',
        'KMF',
        'KPW',
        'KRW',
        'KWD',
        'KYD',
        'KZT',
        'LAK',
        'LBP',
        'LKR',
        'LRD',
        'LSL',
        'LYD',
        'MAD',
        'MDL',
        'MGA',
        'MKD',
        'MMK',
        'MNT',
        'MOP',
        'MRU',
        'MUR',
        'MVR',
        'MWK',
        'MXN',
        'MXV',
        'MYR',
        'MZN',
        'NAD',
        'NGN',
        'NIO',
        'NOK',
        'NPR',
        'NZD',
        'OMR',
        'PAB',
        'PEN',
        'PGK',
        'PHP',
        'PKR',
        'PLN',
        'PYG',
        'QAR',
        'RON',
        'RSD',
        'RUB',
        'RWF',
        'SAR',
        'SBD',
        'SCR',
        'SDG',
        'SEK',
        'SGD',
        'SHP',
        'SLL',
        'SOS',
        'SRD',
        'SSP',
        'STN',
        'SVC',
        'SYP',
        'SZL',
        'THB',
        'TJS',
        'TMT',
        'TND',
        'TOP',
        'TRY',
        'TTD',
        'TWD',
        'TZS',
        'UAH',
        'UGX',
        'USD',
        'USN',
        'UYI',
        'UYU',
        'UYW',
        'UZS',
        'VES',
        'VND',
        'VUV',
        'WST',
        'XAF',
        'XAG',
        'XAU',
        'XBA',
        'XBB',
        'XBC',
        'XBD',
        'XCD',
        'XDR',
        'XOF',
        'XPD',
        'XPF',
        'XPT',
        'XSU',
        'XTS',
        'XUA',
        'XXX',
        'YER',
        'ZAR',
        'ZMW',
        'ZWL',
    ],
    'type_exchange' => [
        1 => 'User com',
        2 => 'Com From Provider',
        5 => 'Pay for Provider',
        7 => 'Pay provider',
        6 => 'Pay for Agent',
        3 => 'Receipt',
        4 => 'Profit',
        8 => 'Flywire com provider',
        9 => 'Flywire com agent',
    ],
    'quarter' => [
        1 => [
            'name' => 'First quarter',
            'value' => json_encode([1, 3]),
        ],
        2 => [
            'name' => 'Second quarter',
            'value' => json_encode([4, 6]),
        ],
        3 => [
            'name' => 'Third quarter',
            'value' => json_encode([7, 9]),
        ],
        4 => [
            'name' => 'Fourth quarter',
            'value' => json_encode([10, 12]),
        ],
    ],
    'type_receipt' => [
        1 => 'Thu tiền bán hàng',
        2 => 'Thu tiền đặt cọc',
        3 => '131',
        4 => '331',
    ],

    'policy_status' => [
        1 => 'Done',
        2 => 'Customer Bank',
        3 => 'Monthly deduct',
        4 => 'Monthly deduct - Annalink',
    ],
    'payment_note_provider' => [
        1 => 'Full payment',
        2 => 'Pay after deducting com',
    ],
    'payment_status' => [
        1 => 'Not initiated',
        2 => 'Initiated',
        3 => 'Guaranteed',
        4 => 'Delivered',
        5 => 'Cancelled',
        6 => 'Refund',
    ],

    'template_export' => [
        1 => '1. Payment request - VND (Edupay Exchange ',
        2 => '2. Payment request - VND (VCB Exchange rate)',
        3 => '3. Payment request - VND (Edupay - deduct)',
        4 => '4. Hoa don thanh toan BHVN',
        5 => '5. Hoa don thanh toan BHVN (full)',
        6 => '6. Payment request - VND (Edupay Exchange rate) - no agent',
        7 => '7. Payment request - VND (VCB Exchange rate) - no agent',
        8 => '8. Hoa don thanh toan BHVN (full) - no agent',
        9 => '9. Invoice - Full payment - bank',
        10 => '10. Invoice - Full payment - Paypal',
        11 => '11. Invoice - deduct - included GST- Bank',
        12 => '12. Invoice - deduct - included GST',
        13 => '13. Invoice - deduct - excluded GST- Bank',
        14 => '14. Invoice - deduct - excluded GST',
        15 => '15. Payment Request - TAX'
    ],

    'type_file' => [
        1 => 'Excel',
        2 => 'Image',
        3 => 'Doc',
        4 => 'PDF',
    ],
    'type_system' => [
        'OSHC' => ['General '],
        'Flywire' => [],
        'Study Tour' => [],
        'Media' => ['Management', 'Email MKT', 'Design', 'MKT support'],
        'Website' => ['SSDH', 'Annalink', 'Annalink Tours', 'OSHC STUDETNS', 'OSHC Global', 'OVHC Global'],
        'FANPAGE' => ['SSDH', 'Annalink', 'Annalink Tours', 'OSHC STUDETNS', 'Tips & Trip'],
        'CRM' => ['Du học', 'Annalink'],
        'Management' => ['Policy', 'Personel', 'Training'],
    ],
    'form_policy_termination' => [
        1 => 'You paid for cover but did not come to Australia',
        2 => 'Your student visa was not extended, was cancelled or a renewal/extension was refused',
        3 => 'You need to leave Australia before the end of your studies and approved preiod of stay',
        4 => 'You have been granted permanent residence in Australia',
        5 => 'You are not living in Australia for 3 months or more',
        6 => 'You can provide proof of OSHC with another organisation',
        7 => 'Change the scale of policy i.e from single to family',
        8 => 'You have been granted a new visa type',
        9 => 'Change to your policy visa start and/or end date',
    ],
    'lang_service_form' => [
        'full_name' => 'Full Name',
        'birth_day_request' => 'Birth Day',
        'email' => 'Email',
        'provider_id' => 'Provider',
        'policy_no' => 'Policy',
        'first_name' => 'First Name',
        'country_id' => 'Country',
        'last_name' => 'Last Name',
        'relationship_dependent' => 'Relationship Dependent',
        'birth_day' => 'Birth Day',
        'new_start_date' => 'New Start Date',
        'termination_date' => 'Termination Date',
        'reason_termination' => 'Reason Termination',
        'passport_no' => 'Passport No',
        'note' => 'Note',
        'type_request' => 'Type Request',
        'tel' => 'Mobile',
        'your-service' => 'Which service are you interested in?',
    ],
    'com_status' => [
        1 => 'Not yet paid',
        2 => 'Paid',
        3 => 'Unpaid',
    ],
    'type_get_data_payment_invoice' => [
        1 => 'Default(Flywire)',
        2 => 'Special(Flywire)',
    ],
    'issue_market_feedback_agent' => [
        1 => 'Insurance',
        2 => 'Flywire',
        3 => 'Study Tours',
        4 => 'Homestay',
        5 => 'Visa',
        6 => 'Others',
    ],
    'issue_competition_feedback_agent' => [
        1 => 'Cohort',
        2 => 'NIB',
        3 => 'SLC',
    ],
    'issue_proposal_agent' => [
        1 => 'Market',
        2 => 'Sale documents',
        3 => 'Website',
        4 => 'CRM',
        5 => 'Others',
    ],
    'type_training_task_sale' => [
        1 => 'Company',
        2 => 'Team',
        3 => 'Personal',
    ],
    'result_training_task_sale' => [
        1 => 'Ok',
        2 => 'Not ok',
    ],
    'type_sale_task_assign' => [
        1 => 'Insurance',
        2 => 'Flywire',
        3 => 'Study Tours',
        4 => 'Homestay',
        5 => 'Visa',
        6 => 'Other',
    ],
    'color_event_google' => [
        1 => 'Blue',
        2 => 'Green',
        3 => 'Purple',
        4 => 'Red',
        5 => 'Yellow',
        6 => 'Orange',
        7 => 'Turquoise',
        8 => 'Gray',
        9 => 'Bold blue',
        10 => 'Bold green',
        11 => 'Bold red',
    ],
    'gst' => [
        1 => 'Included',
        2 => 'Not included',
    ],
    'permission_see' => [
        1 => 'total',
        2 => 'department',
        3 => 'member',
    ],
    'potential_service' => [
        2 => 'OSHC',
        3 => 'OVHC',
        4 => 'Student insurance',
        5 => 'Flywire',
        6 => 'Visitor Insurance',
        7 => 'Homestay',
        8 => 'Study tour',
    ],
    'flywire_status' => [
        1 => 'Initiated',
        2 => 'Verification',
        3 => 'On hold',
        4 => 'Guaranteed',
        5 => 'Delivered',
        6 => 'Cancelled',
    ],
    'type_of_refund_profit' => [
        1 => 'Full refund',
        2 => 'Partial refund',
        3 => 'Downgrade',
        4 => 'Other'
    ],
    'fields_table_agent' => [
        0 => 'Branch',
        1 => 'Name',
        2 => 'Country',
        3 => 'Status',
        4 => 'Market',
        5 => 'Service',
        6 => 'Rating',
        7 => 'Contact',
        8 => 'Com',
        9 => 'Code',
        10 => 'PC',
        11 => 'Registered date',
        12 => 'Creation date',
        13 => 'Note 1',
        14 => 'Note 2',
        15 => 'Type of agent',
        16 => 'Company email',
        17 => 'Tel 1',
        18 => 'Tel 2',
        19 => 'Website',
        20 => 'City',
        21 => 'Department / Office',
        22 => 'Facebook'
    ],
    'task_follow_up_status' => [
        0 => 'Need follow',
        1 => 'Urgent',
        2 => 'Stop follow',
        3 => 'Done'
    ],
    'status_refund_recall' => [
        0 => 'blank',
        1 => 'Not yet',
        2 => 'Done',
        3 => 'Recall'
    ],
    'hospital_access' => [
        0 => 0,
        1 => 250,
        2 => 500,
        3 => 750
    ]
];
